/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;
import java.util.List;

public class App {
    public static void main(String... args) {
        List<String> colors = Lists.newArrayList("Red", "Green", "Blue");

        System.out.println(Lists.reverse(colors));
    }
}
